import "./globals.css";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`h-screen bg-gradient-to-t from-primary to-lightBlue ${poppins.className}`}>
        <div className="mx-auto w-[90%] sm:w-[70%] h-full">{children}</div>
      </body>
    </html>
  );
}
